const sampleData = {
  products: [
    {
      name: "Motosport BMW Hoodie",
      slug: "loose-fit-jogger-sweatshirt",
      category: "Men's Sweatshirts",
      images: [
        "/assets/images/bmw-hoodie.jpg",
        "/assets/images/bmw-hoodie-front.jpg",
      ],
      price: "599.99",
      brand: "Puma",
      rating: "4.5",
      numReviews: 10,
      stock: 5,
      description:
        "BMW sporting elegance with an urban twist. Fall in love with this loose, cozy sweatshirt in super-comfortable double-face piqué.",
      isFeatured: true,
      banner: "/assets/images/bmw-hoodie.jpg",
    },
    {
      name: "BMW SHIRT",
      slug: "BMW-Unisex-shirt-comfortable-and-cozy",
      category: "Men's Shirts",
      images: ["/assets/images/bmwshirt.jpg", "/assets/images/bmwshirt.jpg"],
      price: "199.90",
      brand: "Puma",
      rating: "4.2",
      numReviews: 8,
      stock: 10,
      description:
        "Hit the courts like Novak Djokovic with this shirt, made to move your way.",
      isFeatured: true,
      banner: "/assets/images/bmwshirt.jpg",
    },
    {
      name: "BMW Polo",
      slug: "Stylish-Motosrport-BMW-polo-shirt",
      category: "Polo",
      images: ["/assets/images/bmw-polo.jpg", "/assets/images/p3-2.jpeg"],
      price: "1449.95",
      brand: "Puma",
      rating: "4.9",
      numReviews: 3,
      stock: 0,
      description: "Stay stylish, whatever the weather. Casual and Formal ",
    },
    {
      name: " BMW WOMENS Shirt",
      slug: "womens-sport-french-capsule-tracksuit-shirt",
      category: " Womens Shirts",
      images: ["/assets/images/women-bmw-puma.jpg", "/assets/images/p4-2.jpeg"],
      price: "755.95",
      brand: "Puma",
      rating: "3.6",
      numReviews: 5,
      stock: 10,
      description:
        "A tricolour design brings a distinctive edge to these lightweight tracksuit shirts made of diamond taffeta. ",
    },
    {
      name: "Casual Bags Classic design.",
      slug: "BMW-SIDEBAG",
      category: "Accessories",
      images: ["/assets/images/bmw-bag.jpg"],
      price: "600",
      brand: "BMW",
      rating: "4.0",
      numReviews: 10,
      stock: 20,
      description: " Casual and Classic  Basic Solid Color and polyester bag",
    },
  ],
};
export default sampleData;
